source "https://rubygems.org"
gemspec

gem "jekyll", "~> 3.9.1"

gem "just-the-docs"

gem "jekyll-github-metadata", ">= 2.15"

gem "jekyll-include-cache", group: :jekyll_plugins
gem "jekyll-sitemap", group: :jekyll_plugins

gem "html-proofer", "~> 5.0", :group => :development

gem "kramdown-parser-gfm"
